// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-5SrJIy6lVMhAK5ofGdiKULuagXQt8c',
    appId: '1:881711151953:web:89814fcb59640d8f5a3170',
    messagingSenderId: '881711151953',
    projectId: 'oneul-do',
    authDomain: 'oneul-do.firebaseapp.com',
    storageBucket: 'oneul-do.firebasestorage.app',
    measurementId: 'G-KP7PHB45BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGavH-mq1GcNuBeIvMPuSUf_RwZDImWs',
    appId: '1:881711151953:android:852fedba2c3a628a5a3170',
    messagingSenderId: '881711151953',
    projectId: 'oneul-do',
    storageBucket: 'oneul-do.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmy7uspnZ6h04JornvQoFLttXI8Z_A95M',
    appId: '1:881711151953:ios:428bb03ac7de37a25a3170',
    messagingSenderId: '881711151953',
    projectId: 'oneul-do',
    storageBucket: 'oneul-do.firebasestorage.app',
    iosBundleId: 'com.example.oneul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmy7uspnZ6h04JornvQoFLttXI8Z_A95M',
    appId: '1:881711151953:ios:428bb03ac7de37a25a3170',
    messagingSenderId: '881711151953',
    projectId: 'oneul-do',
    storageBucket: 'oneul-do.firebasestorage.app',
    iosBundleId: 'com.example.oneul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM-5SrJIy6lVMhAK5ofGdiKULuagXQt8c',
    appId: '1:881711151953:web:6a3267fde5a7a1df5a3170',
    messagingSenderId: '881711151953',
    projectId: 'oneul-do',
    authDomain: 'oneul-do.firebaseapp.com',
    storageBucket: 'oneul-do.firebasestorage.app',
    measurementId: 'G-5ZEFNSRWPF',
  );
}
